### ISSUE TITLE
Implement customers coming in and generating orders

### ISSUE THREAD

**Issue by outfrost** [outfrost/ld49#4]

**Comment by Kiskadee-dev** [comment]
Customer spawning created by 6ab9e48cd98a54ce3bb754ffbcc0d4af19746bed

**Comment by Kiskadee-dev** [comment]
- [ ] Customer order repository
- [ ] Customer comes and wait until satisfied or enraged enough to leave?
- [ ] Make the customers go away and despawn when done.
