### ISSUE TITLE
Apparently a customer can get stuck picking up their coffee

### ISSUE THREAD

**Issue by outfrost** [outfrost/ld49#50]
When a customer happens to be the first one in queue, and you call them to pick up beverages, they'll pick up the false order, then go place their actual order, and get stuck while trying to pick that up later.

**Comment by outfrost** [comment]
Anything that isn't the customer's actual order. So, they'll be picking something up, and it can be an empty or non-empty tray, but it's not actually their turn to pick it up.

**Comment by 666Savior** [comment]
Customers no longer can be clicked on unless they have placed order and are at a waiting spot
Customer state machine rework appears to have corrected this
Confirmed that you cannot click on customers while they are waiting to order, moving to place order, waiting at register, moving to wait position
